github:
  description: "Apache Creadur RAT - Release Audit Tool"
  homepage: https://creadur.apache.org/
  labels:
    - maven
    - java
    - cli
    - licensechecker 
    - apache
    - creadur
    - rat
  autolink_jira:
    - RAT
    - WHISKER
    - TENTACLES

notifications:
  commits:      commits@creadur.apache.org
