language: java
dist: trusty
sudo: required

jobs:
    include:
        - name: "Java 8"
          jdk: openjdk8
          script: mvn -e -B -V clean package site

        - name: "Java 11"
          jdk: openjdk11
          script: mvn -e -B -V clean package site

        - name: "Java 17"
          jdk: openjdk17
          script: mvn -e -B -V clean package site
