#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DEVHINT: RAT-302: Do not use modern JDK due to the javadoc problem; JDK8 and 16 are okay
# DEVHINT: package build is required as site target requires access to the completed jar package.
# no clean as we would wipe the release JARs
./mvnw -B package site site:stage

# DEVHINT: with trailing slash please!
targetDirectory=../creadur-site/rat/

echo "Copying site resources into asf-site repo under $targetDirectory"
cp -rvf target/staging/* $targetDirectory > /dev/null
echo "DONE."

echo
echo "Copying JS/CSS resources into generated reports"
for subdirectory in "apidocs" "testapidocs" "xref" "xref-test"
 do
  echo "> $subdirectory"
  mkdir -p $targetDirectory/$subdirectory && cp -rvf src/site/javadocFont/* $targetDirectory/$subdirectory/ > /dev/null
 done
echo "DONE."

echo
echo "Fixing missing JS/CSS resources in all subprojects"
for module in "apache-rat" "apache-rat-core" "apache-rat-plugin" "apache-rat-tasks" "apache-rat-testdata" "apache-rat-tools"
 do
  echo ">> Module: $module"
   for targetSubdirectory in "apidocs" "testapidocs" "xref" "xref-test"
   do
     mkdir -p $targetDirectory$module/$targetSubdirectory && cp -rvf src/site/javadocFont/* $targetDirectory$module/$targetSubdirectory/ > /dev/null
   done
 done

echo "DONE."
