/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

${package}

import org.apache.commons.cli.Option;
import org.apache.commons.lang3.StringUtils;
import org.apache.rat.commandline.Arg;
import org.apache.rat.DeprecationReporter;
import org.apache.rat.utils.DefaultLog;
import org.apache.rat.utils.Log;
${baseImport}

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/* DO NOT EDIT - GENERATED FILE */

/**
 * Build RAT tool command line arguments from Gradle properties.
 *
 * <p>This interface is generated by the RAT code generator for Gradle. Do not edit.
 */
@SuppressWarnings({"StringOperationCanBeSimplified", "SimplifyStreamApiCallChains", "DataFlowIssue", "ArraysAsListWithZeroOrOneArgument", "deprecation"})
${class}

    private static final Map<String, String> xlateName = new HashMap<>();
    private static final List<String> unsupportedArgs = new ArrayList<>();
    private static final Map<String, String> deprecatedArgs = new HashMap<>();

    static {
${static}
    }

    /**
     * Returns the list of unsupported args.
     * @return the list of kebab style names that are unsupported by the Gradle plugin.
     */
    public static List<String> unsupportedArgs() {
        return Collections.unmodifiableList(unsupportedArgs);
    }

${constructor}
${constructorBody}

${converterBody}
    }

    public Map<String, List<String>> getArgsMap() {
        Map<String, List<String>> map = new HashMap<>();
        args.forEach((k, l) -> map.put(k, new ArrayList<>(l)));
        return map;
    }

    /**
     * Reads values for the Arg.
     *
     * @param arg The Arg to get the values for.
     * @return The list of values or an empty list.
     */
    public List<String> getValues(final Arg arg) {
        List<String> result = new ArrayList<>();
        for (Option option : arg.group().getOptions()) {
            if (option.getLongOpt() != null) {
                List<String> args = getArg(option.getLongOpt());
                if (args != null) {
                    result.addAll(args);
                }
            }
        }
        return result;
    }

    /**
     * Removes all values for an Arg.
     * @param arg The arg to remove values for.
     */
    public void removeKey(final Arg arg) {
        for (Option option : arg.group().getOptions()) {
            if (option.getLongOpt() != null) {
                removeArg(option.getLongOpt());
            }
        }
    }

${commonArgs}
}
