/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

${package}

import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.MapProperty;

/* DO NOT EDIT - GENERATED FILE */

/**
 * Generated class providing all RAT options in the "Gradle way".
 *
 * <p>This interface is generated by the RAT code generator for Gradle. Do not edit.
 */
@SuppressWarnings({"NullableProblems", "DeprecatedIsStillUsed", "UnstableApiUsage"})
${interface}

${properties}
    /**
     * Apply the configuration options of the given instance as conventions to this instance.
     * @param from The instance to apply the conventions from.
     */
${applyConventions}
}
